"""initial_bot_schema

Revision ID: 289c17a09fbb
Revises:
Create Date: 2026-04-02 08:43:25.178422

Deployment target: Postgres / Supabase. Also applies cleanly to SQLite for local autogenerate checks.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '289c17a09fbb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('model_path', sa.Text(), nullable=False),
    sa.Column('model_filename', sa.String(), nullable=True),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('img_size', sa.Integer(), nullable=False),
    sa.Column('tp_pct', sa.Float(), nullable=True),
    sa.Column('sl_pct', sa.Float(), nullable=True),
    sa.Column('runtime_days', sa.Integer(), nullable=True),
    sa.Column('run_time', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('lifecycle_state', sa.String(), nullable=False),
    sa.Column('starting_capital', sa.Float(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('position_size_pct', sa.Float(), nullable=False),
    sa.Column('commission_pct', sa.Float(), nullable=False),
    sa.Column('slippage_pct', sa.Float(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_signal', sa.String(), nullable=True),
    sa.Column('last_confidence', sa.Float(), nullable=True),
    sa.Column('last_chart_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bots_lifecycle_state'), 'bots', ['lifecycle_state'], unique=False)
    op.create_index(op.f('ix_bots_user_id'), 'bots', ['user_id'], unique=False)
    op.create_table('bot_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bot_id', sa.String(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('run_finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('signal', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('chart_path', sa.Text(), nullable=True),
    sa.Column('heatmap_path', sa.Text(), nullable=True),
    sa.Column('chart_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('equity', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('run_metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_runs_bot_id'), 'bot_runs', ['bot_id'], unique=False)
    op.create_table('bot_equity_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bot_id', sa.String(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_equity', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=True),
    sa.Column('bot_run_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bot_run_id'], ['bot_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_equity_snapshots_as_of'), 'bot_equity_snapshots', ['as_of'], unique=False)
    op.create_index(op.f('ix_bot_equity_snapshots_bot_id'), 'bot_equity_snapshots', ['bot_id'], unique=False)
    op.create_table('bot_trades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bot_id', sa.String(), nullable=False),
    sa.Column('prediction_run_id', sa.String(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('position_notional', sa.Float(), nullable=False),
    sa.Column('tp_price', sa.Float(), nullable=True),
    sa.Column('sl_price', sa.Float(), nullable=True),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(), nullable=True),
    sa.Column('exit_run_id', sa.String(), nullable=True),
    sa.Column('pnl_amount', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exit_run_id'], ['bot_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prediction_run_id'], ['bot_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_trades_bot_id'), 'bot_trades', ['bot_id'], unique=False)
    op.create_index(op.f('ix_bot_trades_prediction_run_id'), 'bot_trades', ['prediction_run_id'], unique=False)
    op.create_index(op.f('ix_bot_trades_status'), 'bot_trades', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_trades_status'), table_name='bot_trades')
    op.drop_index(op.f('ix_bot_trades_prediction_run_id'), table_name='bot_trades')
    op.drop_index(op.f('ix_bot_trades_bot_id'), table_name='bot_trades')
    op.drop_table('bot_trades')
    op.drop_index(op.f('ix_bot_equity_snapshots_bot_id'), table_name='bot_equity_snapshots')
    op.drop_index(op.f('ix_bot_equity_snapshots_as_of'), table_name='bot_equity_snapshots')
    op.drop_table('bot_equity_snapshots')
    op.drop_index(op.f('ix_bot_runs_bot_id'), table_name='bot_runs')
    op.drop_table('bot_runs')
    op.drop_index(op.f('ix_bots_user_id'), table_name='bots')
    op.drop_index(op.f('ix_bots_lifecycle_state'), table_name='bots')
    op.drop_table('bots')
    # ### end Alembic commands ###
